/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as DocsLImport } from './routes/docs/_l'
import { Route as LayoutOnboardingExtensionIndexImport } from './routes/_layout.onboarding/extension/index'
import { Route as DocsLGettingStartedLImport } from './routes/docs/_l.getting-started/_l'
import { Route as DocsLGettingStartedLWhatIsEthuiImport } from './routes/docs/_l.getting-started/_l.what-is-ethui'

// Create Virtual Routes

const DocsImport = createFileRoute('/docs')()
const DocsLGettingStartedImport = createFileRoute('/docs/_l/getting-started')()

// Create/Update Routes

const DocsRoute = DocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocsLRoute = DocsLImport.update({
  id: '/_l',
  getParentRoute: () => DocsRoute,
} as any)

const DocsLGettingStartedRoute = DocsLGettingStartedImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsLRoute,
} as any)

const LayoutOnboardingExtensionIndexRoute =
  LayoutOnboardingExtensionIndexImport.update({
    id: '/onboarding/extension/',
    path: '/onboarding/extension/',
    getParentRoute: () => LayoutRoute,
  } as any)

const DocsLGettingStartedLRoute = DocsLGettingStartedLImport.update({
  id: '/_l',
  getParentRoute: () => DocsLGettingStartedRoute,
} as any)

const DocsLGettingStartedLWhatIsEthuiRoute =
  DocsLGettingStartedLWhatIsEthuiImport.update({
    id: '/what-is-ethui',
    path: '/what-is-ethui',
    getParentRoute: () => DocsLGettingStartedLRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsImport
      parentRoute: typeof rootRoute
    }
    '/docs/_l': {
      id: '/docs/_l'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsLImport
      parentRoute: typeof DocsRoute
    }
    '/docs/_l/getting-started': {
      id: '/docs/_l/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsLGettingStartedImport
      parentRoute: typeof DocsLImport
    }
    '/docs/_l/getting-started/_l': {
      id: '/docs/_l/getting-started/_l'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsLGettingStartedLImport
      parentRoute: typeof DocsLGettingStartedRoute
    }
    '/_layout/onboarding/extension/': {
      id: '/_layout/onboarding/extension/'
      path: '/onboarding/extension'
      fullPath: '/onboarding/extension'
      preLoaderRoute: typeof LayoutOnboardingExtensionIndexImport
      parentRoute: typeof LayoutImport
    }
    '/docs/_l/getting-started/_l/what-is-ethui': {
      id: '/docs/_l/getting-started/_l/what-is-ethui'
      path: '/what-is-ethui'
      fullPath: '/docs/getting-started/what-is-ethui'
      preLoaderRoute: typeof DocsLGettingStartedLWhatIsEthuiImport
      parentRoute: typeof DocsLGettingStartedLImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutOnboardingExtensionIndexRoute: typeof LayoutOnboardingExtensionIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutOnboardingExtensionIndexRoute: LayoutOnboardingExtensionIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface DocsLGettingStartedLRouteChildren {
  DocsLGettingStartedLWhatIsEthuiRoute: typeof DocsLGettingStartedLWhatIsEthuiRoute
}

const DocsLGettingStartedLRouteChildren: DocsLGettingStartedLRouteChildren = {
  DocsLGettingStartedLWhatIsEthuiRoute: DocsLGettingStartedLWhatIsEthuiRoute,
}

const DocsLGettingStartedLRouteWithChildren =
  DocsLGettingStartedLRoute._addFileChildren(DocsLGettingStartedLRouteChildren)

interface DocsLGettingStartedRouteChildren {
  DocsLGettingStartedLRoute: typeof DocsLGettingStartedLRouteWithChildren
}

const DocsLGettingStartedRouteChildren: DocsLGettingStartedRouteChildren = {
  DocsLGettingStartedLRoute: DocsLGettingStartedLRouteWithChildren,
}

const DocsLGettingStartedRouteWithChildren =
  DocsLGettingStartedRoute._addFileChildren(DocsLGettingStartedRouteChildren)

interface DocsLRouteChildren {
  DocsLGettingStartedRoute: typeof DocsLGettingStartedRouteWithChildren
}

const DocsLRouteChildren: DocsLRouteChildren = {
  DocsLGettingStartedRoute: DocsLGettingStartedRouteWithChildren,
}

const DocsLRouteWithChildren = DocsLRoute._addFileChildren(DocsLRouteChildren)

interface DocsRouteChildren {
  DocsLRoute: typeof DocsLRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsLRoute: DocsLRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/docs': typeof DocsLRouteWithChildren
  '/docs/getting-started': typeof DocsLGettingStartedLRouteWithChildren
  '/onboarding/extension': typeof LayoutOnboardingExtensionIndexRoute
  '/docs/getting-started/what-is-ethui': typeof DocsLGettingStartedLWhatIsEthuiRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/docs': typeof DocsLRouteWithChildren
  '/docs/getting-started': typeof DocsLGettingStartedLRouteWithChildren
  '/onboarding/extension': typeof LayoutOnboardingExtensionIndexRoute
  '/docs/getting-started/what-is-ethui': typeof DocsLGettingStartedLWhatIsEthuiRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/docs/_l': typeof DocsLRouteWithChildren
  '/docs/_l/getting-started': typeof DocsLGettingStartedRouteWithChildren
  '/docs/_l/getting-started/_l': typeof DocsLGettingStartedLRouteWithChildren
  '/_layout/onboarding/extension/': typeof LayoutOnboardingExtensionIndexRoute
  '/docs/_l/getting-started/_l/what-is-ethui': typeof DocsLGettingStartedLWhatIsEthuiRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/docs'
    | '/docs/getting-started'
    | '/onboarding/extension'
    | '/docs/getting-started/what-is-ethui'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/docs'
    | '/docs/getting-started'
    | '/onboarding/extension'
    | '/docs/getting-started/what-is-ethui'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/docs'
    | '/docs/_l'
    | '/docs/_l/getting-started'
    | '/docs/_l/getting-started/_l'
    | '/_layout/onboarding/extension/'
    | '/docs/_l/getting-started/_l/what-is-ethui'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/docs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/onboarding/extension/"
      ]
    },
    "/docs": {
      "filePath": "docs",
      "children": [
        "/docs/_l"
      ]
    },
    "/docs/_l": {
      "filePath": "docs/_l.tsx",
      "parent": "/docs",
      "children": [
        "/docs/_l/getting-started"
      ]
    },
    "/docs/_l/getting-started": {
      "filePath": "docs/_l.getting-started",
      "parent": "/docs/_l",
      "children": [
        "/docs/_l/getting-started/_l"
      ]
    },
    "/docs/_l/getting-started/_l": {
      "filePath": "docs/_l.getting-started/_l.tsx",
      "parent": "/docs/_l/getting-started",
      "children": [
        "/docs/_l/getting-started/_l/what-is-ethui"
      ]
    },
    "/_layout/onboarding/extension/": {
      "filePath": "_layout.onboarding/extension/index.tsx",
      "parent": "/_layout"
    },
    "/docs/_l/getting-started/_l/what-is-ethui": {
      "filePath": "docs/_l.getting-started/_l.what-is-ethui.tsx",
      "parent": "/docs/_l/getting-started/_l"
    }
  }
}
ROUTE_MANIFEST_END */
